// Code generated by hertz generator.

package demo_repo

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	demo_repo "github.com/dongzwhitsz/llm_test/biz/model/dongzwhitsz/llm_test/demo_repo"
)

// HelloMethod .
// @router /hello [GET]
func HelloMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req demo_repo.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(demo_repo.HelloResp)

	c.JSON(consts.StatusOK, resp)
}
