// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	dongzwhitsz_llm_test_demo_repo "github.com/dongzwhitsz/llm_test/biz/router/dongzwhitsz/llm_test/demo_repo"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	dongzwhitsz_llm_test_demo_repo.Register(r)
}
